services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    image: quay.io/debezium/kafka:3.1
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  postgres:
    image: quay.io/debezium/example-postgres:3.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init/db/populate.sql:/docker-entrypoint-initdb.d/populate.sql

  connect:
    image: quay.io/debezium/connect:3.1
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - postgres
    links:
      - kafka
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  backend:
    image: ghcr.io/aldinkapetanovic/test-events-latency-pg-debezium-kafka-node-backend:latest
    depends_on:
      - kafka
      - connect
      - postgres
      - curl-runner
  curl-runner:
    image: curlimages/curl:latest
    depends_on:
      - connect
    volumes:
      - ./init/curl-runner/register-postgres.json:/config/register-postgres.json
      - ./init/curl-runner/entrypoint.sh:/entrypoint.sh
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
